//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaratonWeb.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maraton
    {
        public Maraton()
        {
            this.ResultadoMaratonParticipantes = new HashSet<ResultadoMaratonParticipante>();
        }
    
        public int IdMaraton { get; set; }
        public string Nombre { get; set; }
        public int MaxParticipantes { get; set; }
        public string LugarSalida { get; set; }
        public int ParticipantesEnEspera { get; set; }
        public int PrimerPremio { get; set; }
        public int SegundoPremio { get; set; }
        public int TercerPremio { get; set; }
        public Nullable<System.DateTime> FechaHorarioComienzo { get; set; }
    
        public virtual ICollection<ResultadoMaratonParticipante> ResultadoMaratonParticipantes { get; set; }
    }
}
